### ISSUE TITLE
clean out star catalogue

### ISSUE THREAD

**Issue by cha-ron** [brannondorsey/FermiGameJam#9]
we only need a handful of the columns (`id`, `rarad`, `decrad`, `dist`, `x`, `y`, `z` are the ones that come to mind), and a number of rows (sol (`id` == 0), `dist` >= 100000) can be thrown out altogether, so we don't have to filter them

**Comment by brannondorsey** [comment]
Interesting fields include: `absmag`, `spect`, `comp, comp_primary, base`
